import { Geist, Geist_Mono } from "next/font/google";
import { FilterOptions } from "./type";
import { Metadata } from "next";

const API_BASE_URL =
  "https://uat-pract-mahennekkers27-2401-mahens-projects-240b520d.vercel.app";
const DEBOUNCE_DELAY = 500;

const DEFAULT_FILTER_OPTIONS: FilterOptions = {
  features: [],
  priorities: ["low", "medium", "high", "critical"],
  statuses: ["open", "closed", "in_progress", "resolved"],
};

const COLUMNTEXT = [
  { label: "Status", align: "left" },
  { label: "Priority", align: "left" },
  { label: "Feature", align: "left" },
  { label: "Test Scenario", align: "left" },
  { label: "Description", align: "left" },
  { label: "Author", align: "left" },
  { label: "Updated", align: "left" },
  { label: "Actions", align: "center" },
];

const ITEMS_PER_PAGE = 3;

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export {
  API_BASE_URL,
  DEBOUNCE_DELAY,
  DEFAULT_FILTER_OPTIONS,
  COLUMNTEXT,
  ITEMS_PER_PAGE,
  geistSans,
  geistMono,
  metadata,
};
